### PR TITLE
Rename module

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
I didn't like the way `k8c.io/apis/pkg/apis/....` looked like, so currently the API packages are not grouped in a shared directory at all. That also looks bad and so I convinced @embik to rename the module to `api`, so import paths will later be `k8c.io/api/pkg/apis/....`. This is also closer to Kubernetes upstream repos would be named.

This also undoes my overeager separation of some constants. I had moved things like OS names and provider names out into a standalone `types` package, but that was too much change, as our goal for now is to migrate KKP 2.x and that should be made as easy as possible. Does not mean we blindly copy _all_ the API code over, but we also don't have to overdo it with cleanup attempts (@xrstf...)

I re-orged the repo from

```
./pkg
├── apps.kubermatic
│   └── v1
├── kubermatic
│   └── v1
├── machine-controller
├── open-policy-agent
├── semver
├── test
│   └── diff
└── types
```

to a more sane

```
./pkg
├── apis
│   ├── apps.kubermatic
│   │   └── v1
│   ├── kubermatic
│   │   └── v1
│   ├── machine-controller
│   └── open-policy-agent
├── semver
└── test
    └── diff
```

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Well you say that, Prow, but yet my command worked and the bogus job is gone. So ... I win!

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
